sqlplus -s system/oracle << EOF
whenever sqlerror exit sql.sqlcode;
set echo off 
set heading off

/* script Initial Version  */
CREATE ROLE "DB_CONNECT";

GRANT CREATE SESSION TO "DB_CONNECT";

CREATE ROLE "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE TYPE TO "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE MATERIALIZED VIEW TO "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE TRIGGER TO "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE PROCEDURE TO "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE SEQUENCE TO "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE VIEW TO "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE SYNONYM TO "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE TABLE TO "SDLCEVOLUTION_OWNER_ROLE";

GRANT CREATE SESSION TO "SDLCEVOLUTION_OWNER_ROLE";

CREATE ROLE "SDLCEVOLUTION_READONLY";

GRANT "DB_CONNECT" TO "SDLCEVOLUTION_READONLY";

GRANT CREATE SYNONYM TO "SDLCEVOLUTION_READONLY";

CREATE ROLE "SDLCEVOLUTION_UPDATE";

CREATE ROLE "SDLCEVOLUTION_APPLICATION";

GRANT "SDLCEVOLUTION_READONLY" TO "SDLCEVOLUTION_APPLICATION";

GRANT "SDLCEVOLUTION_UPDATE" TO "SDLCEVOLUTION_APPLICATION";


CREATE USER "SDLCEVOLUTION_OWNER" IDENTIFIED BY "SDLCEVOLUTION_OWNER"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER "SDLCEVOLUTION_OWNER" QUOTA UNLIMITED ON USERS;

GRANT SDLCEVOLUTION_OWNER_ROLE TO SDLCEVOLUTION_OWNER;

ALTER USER "SDLCEVOLUTION_OWNER" DEFAULT ROLE "SDLCEVOLUTION_OWNER_ROLE";

CREATE USER "SDLCEVOLUTION_USER" IDENTIFIED BY "SDLCEVOLUTION_USER"
TEMPORARY TABLESPACE "TEMP";

GRANT SDLCEVOLUTION_APPLICATION TO SDLCEVOLUTION_USER;

ALTER USER "SDLCEVOLUTION_USER" DEFAULT ROLE "SDLCEVOLUTION_APPLICATION";

exit;
EOF
