name             'mozilla-firefox'
maintainer       'Brian Pitts'
maintainer_email 'brian.pitts@lonelyplanet.com'
license          'Apache v2.0'
description      'Installs/Configures mozilla-firefox'
long_description 'Installs/Configures mozilla-firefox'
version          '0.1.1'
supports         'ubuntu'

depends          'ark'
